version: '3.3'
services:
    app:
      build: 
        context: .
        dockerfile: Dockerfile
      volumes: 
        - ./src:/home/src
        - ./dataset:/home/dataset
        - ./output:/home/output
        - ./data_for_dpt:/home/data_for_dpt
        - ./output_dpt:/home/output_dpt
        - ./tmp:/root/stanza_resources